// GENERATED by tools/readme-examples.py from README.md. Do not edit: edit the page.
@file:Suppress("unused", "UNUSED_PARAMETER", "UNUSED_VARIABLE", "RedundantSuspendModifier")

package readme

import io.github.youndie.petich.*
import kotlin.test.assertEquals
import kotlin.time.Duration.Companion.minutes

val order = petichDefinition<OrderPayload>("order") {
    validate("in-stock", InStock(stock))
    authorize("within-limits", WithinLimits(limits))
    step("hold-funds", HoldFunds(payments))
    step("reserve", ReserveStock(stock))
    announce("confirmed", AnnounceOrder(events))
}

class ReserveStock(private val stock: StockRepository) : PetichStep<OrderPayload> {
    override suspend fun execute(ctx: PetichStepContext, payload: OrderPayload) {
        stock.reserve(payload.sku, payload.quantity)
    }

    override suspend fun compensate(ctx: PetichStepContext, payload: OrderPayload) {
        stock.release(payload.sku, payload.quantity)
    }
}

class InStock(private val stock: StockRepository) : PetichCheck<OrderPayload> {
    override suspend fun check(ctx: PetichCheckContext, payload: OrderPayload) {
        if (!stock.has(payload.sku, payload.quantity)) ctx.reject("out of stock")
    }
}

class AnnounceOrder(private val events: OrderEvents) : PetichAnnouncement<OrderPayload> {
    override suspend fun announce(ctx: PetichAnnouncementContext, payload: OrderPayload) {
        ctx.emit(events.confirmed(ctx.petich.id, payload))
    }
}

internal suspend fun example7(ctx: PetichStepContext) {
ctx.suspendFor("CONFIRM", ttl = 5.minutes)
}

internal suspend fun example8(ctx: PetichStepContext) {
val probe = PetichMemberProbe(saga, stepKey = "capture")
CaptureStep(payments).compensate(probe, payload)

assertEquals(emptyList(), payments.refunded)   // nothing was recorded, so nothing is given back
}

internal class Example9 : ReadmeStep() {
override suspend fun execute(ctx: PetichStepContext, payload: OrderPayload) {
    stock.reserve(ctx.idempotencyKey, payload.sku, payload.quantity)
}

override suspend fun compensate(ctx: PetichStepContext, payload: OrderPayload) {
    stock.releaseByKey(ctx.idempotencyKey)   // a no-op when there is nothing under that name
}
}

internal suspend fun example10(ctx: PetichStepContext) {
board.offer(ctx.idempotencyKey(driverId), payload.rideId, driverId)
}

internal class Example11 : ReadmeStep() {
override suspend fun compensate(ctx: PetichStepContext, payload: OrderPayload) {
    // The replay is the point: if the first call landed, this returns ITS answer and no second
    // hold is taken; if it never landed, this creates one and the line below removes it. The net
    // is zero either way, which is what the record could not tell us.
    val hold = payments.hold(ctx.idempotencyKey, payload.paymentMethodId, payload.amount)
    payments.release(hold.id)
}
}

