#!/usr/bin/env python3
"""Do the README's examples still compile against the library?

B-45 found eight places where the page described a model the code no longer had. Every one survived
for the same reason: prose beside code is checked by nobody. `make check` reads documents and
`./gradlew build` reads sources; neither compiles a fenced block. The sharpest of the eight shows it
is not carelessness — "step and announce take members that act" was TRUE when it was written and
became false when B-41 merged, four hours before a reader found it. No care at the keyboard catches
that; a compiler does.

So this compiles them. Every ```kotlin block in README.md is spliced into one file in
`tools/readme-probe/`, which resolves petich as a CONSUMER does — from a publication, never from
`project(":petich-core")` — and the file is compiled.

A block says how it should be placed with an HTML comment on the line before its fence:

    <!-- readme-probe: skip -->     not Kotlin at all, or a fragment that names nothing real
    <!-- readme-probe: statements --> statements, spliced into a function where the page's nouns
                                      (ctx, payload, stock, board, …) are in scope
    <!-- readme-probe: members -->   member declarations, spliced into a class that implements
                                      PetichStep<OrderPayload>
    (no comment)                      a top-level declaration or expression, taken as it stands

A marker rather than a list of line numbers, because a list of line numbers is a second thing to
keep in step with the page, and it would rot exactly the way the page did.

Usage, after a local publication of the version to check against:

    ./gradlew publishToMavenLocal -PVERSION=<v>
    python3 tools/readme-examples.py <v>

`--repository <url>` asks the same question against a real repository, which is what a reader
actually faces.
"""
import argparse
import pathlib
import re
import subprocess
import urllib.request
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
PROBE = ROOT / "tools" / "readme-probe"
GENERATED = PROBE / "src" / "main" / "kotlin" / "Examples.kt"
MARKER = re.compile(r"<!--\s*readme-probe:\s*(\w+)\s*-->")


FENCE = re.compile(r"^(\s*)```kotlin\s*$")


def blocks(text):
    """Every ```kotlin block with the placement its preceding marker asks for.

    Fences are matched with their indentation, because the page puts one inside a bullet list and a
    check that silently skipped it would be a check with a hole the size of one example.
    """
    lines = text.splitlines()
    found, i = [], 0
    while i < len(lines):
        opened = FENCE.match(lines[i])
        if opened:
            indent = opened.group(1)
            placement = "toplevel"
            back = i - 1
            while back >= 0 and not lines[back].strip():
                back -= 1
            if back >= 0:
                marked = MARKER.search(lines[back])
                if marked:
                    placement = marked.group(1)
            body, i = [], i + 1
            while i < len(lines) and lines[i].strip() != "```":
                body.append(lines[i][len(indent):] if lines[i].startswith(indent) else lines[i])
                i += 1
            found.append((placement, len(found) + 1, "\n".join(body)))
        i += 1
    return found


def render(found):
    out = [
        "// GENERATED by tools/readme-examples.py from README.md. Do not edit: edit the page.",
        "@file:Suppress(\"unused\", \"UNUSED_PARAMETER\", \"UNUSED_VARIABLE\", \"RedundantSuspendModifier\")",
        "",
        "package readme",
        "",
        "import io.github.youndie.petich.*",
        "import kotlin.test.assertEquals",
        "import kotlin.time.Duration.Companion.minutes",
        "",
    ]
    kept = 0
    for placement, n, body in found:
        if placement == "skip":
            continue
        kept += 1
        if placement == "statements":
            out += [
                f"internal suspend fun example{n}(ctx: PetichStepContext) {{",
                body,
                "}",
                "",
            ]
        elif placement == "members":
            out += [
                f"internal class Example{n} : ReadmeStep() {{",
                body,
                "}",
                "",
            ]
        elif placement == "toplevel":
            out += [body, ""]
        else:
            raise SystemExit(f"README block {n}: unknown placement {placement!r}")
    return "\n".join(out), kept


def compiler_version():
    """The compiler the BUILD uses, followed to where it lives rather than spelled out here.

    `kotlin` is not a line in this repository's catalogue any more: it comes from `wip`, the
    catalogue a sborka release publishes. `native-consumer-probe.py` follows it the same way and for
    the same reason — a version written out here would be a second number to keep in step, and a
    probe that quietly fell back to another compiler would answer a question nobody asked.
    """
    catalogue = (ROOT / "gradle" / "libs.versions.toml").read_text()
    pin = re.search(r'^sborka\s*=\s*"([^"]+)"', catalogue, re.M)
    if not pin:
        raise SystemExit("no `sborka = \"...\"` in gradle/libs.versions.toml")
    url = (
        "https://reposilite.kotlin.website/snapshots/io/github/youndie/sborka/catalog/"
        f"{pin.group(1)}/catalog-{pin.group(1)}.toml"
    )
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            shared = response.read().decode()
    except OSError as error:
        raise SystemExit(f"cannot read the shared catalogue at {url}: {error}")
    found = re.search(r'^kotlin\s*=\s*"([^"]+)"', shared, re.M)
    if not found:
        raise SystemExit(f"no `kotlin = \"...\"` in {url}")
    return found.group(1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("version")
    ap.add_argument("--repository")
    # THE TWO HALVES ARE SEPARABLE ON PURPOSE. The assembled file lives in the working tree, and in
    # this portfolio the working tree is synchronised one way onto the build host — so generating on
    # the host and then synchronising again overwrites what was just generated with the stale copy
    # from the other side. Emit where you edit, compile where you build.
    ap.add_argument(
        "--emit-only",
        action="store_true",
        help="assemble the file and stop, without compiling",
    )
    args = ap.parse_args()

    found = blocks(README.read_text())
    if not found:
        raise SystemExit("no ```kotlin blocks in README.md — the extractor is broken, not the page")
    source, kept = render(found)
    GENERATED.write_text(source + "\n")
    print(f"{kept} of {len(found)} README blocks are Kotlin to be compiled -> {GENERATED.relative_to(ROOT)}")
    if args.emit_only:
        return 0

    kotlin = compiler_version()

    cmd = [
        str(ROOT / "gradlew"), "-p", str(PROBE), "compileKotlin",
        f"-Pprobe.petichVersion={args.version}",
        f"-Pprobe.kotlinVersion={kotlin}",
        "--no-daemon", "--console=plain",
    ]
    if args.repository:
        cmd.append(f"-Pprobe.repository={args.repository}")

    print(f"$ {' '.join(cmd)}\n", flush=True)
    done = subprocess.run(cmd, cwd=ROOT)
    if done.returncode != 0:
        print("\nREADME EXAMPLES DO NOT COMPILE — the page describes an API the library does not have")
        return 1
    print("\nthe page's examples compile against petich " + args.version)
    return 0


if __name__ == "__main__":
    sys.exit(main())
